project:
  type: website

website:
  title: 76616c6172

  navbar:
    foreground: gray-100
    background: black
    left:
      - text: "About"
        href: index.html
      - href: blog.qmd

  twitter-card: true

  sidebar:
    search: true

  page-footer:
    foreground: gray-100
    background: black
    center:
      - text: "76616c6172"
        href: https://twitter.com/76616c6172

format:
  html:
    theme:
      light: theme_light.scss
      dark: theme_dark.scss
    toc: true
    toc-depth: 5
