project:
  type: website

website:
  title: 76616c6172
  reader-mode: false
  google-analytics:
    tracking-id: "G-9ZP5Z333RG"
    anonymize-ip: false

  navbar:
    collapse: false 
    foreground: white
    background: black
    left:
      - text: "About"
        href: index.html
      - href: blog.qmd

  twitter-card: true

  sidebar:
    search: true

  page-footer:
    foreground: white
    background: black
    center:
      - icon: twitter
        href: https://twitter.com/76616c6172

format:
  html:
    theme:
      light: theme_light.scss
      dark: theme_dark.scss
    toc: true
    toc-depth: 5
